apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-vx-svc
  labels:
    app: k8s-demo-vx
    app.kubernetes.io/name: k8s-demo-vx-svc
    app.kubernetes.io/component: server
spec:
  selector:
    app: k8s-demo-vx
  ports:
    - name: http
      port: 80
      targetPort: http-app
